INFO 2020-11-28 13:41:29,164 root : Сервер доступний. Час на сервері: 2020-11-28T11:41:29.158
INFO 2020-11-28 13:41:29,164 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-11-28 13:41:29,164 root : Відповідь сервера місти наступні поля:
INFO 2020-11-28 13:41:29,165 root : Ключ: date, Значення: 2020-11-28T11:41:29.158
INFO 2020-11-28 13:41:29,165 root : Ключ: current_page, Значення: http://localhost:8000/health/
INFO 2020-11-28 13:41:29,165 root : Ключ: Info_server, Значення: posix
INFO 2020-11-28 13:41:29,165 root : Ключ: client_info, Значення: python-requests/2.23.0
WARNING 2020-11-28 13:49:41,058 root : Сторінка не відповідає
ERROR 2020-11-28 13:49:41,058 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f080021a370>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 13:50:23,636 root : Сторінка не відповідає
ERROR 2020-11-28 13:50:23,637 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdb9aa09370>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 14:12:01,727 root : Page is unable
ERROR 2020-11-28 14:12:01,727 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f076adfa2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 14:18:06,484 root : Сторінка не відповідає
ERROR 2020-11-28 14:18:06,484 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be6f992e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 14:18:20,140 root : Сторінка не відповідає
ERROR 2020-11-28 14:18:20,141 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb3e2412e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 14:22:24,415 root : Сторінка не відповідає
ERROR 2020-11-28 14:22:24,416 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f677a83c2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING 2020-11-28 14:27:10,301 root : Сторінка не відповідає
ERROR 2020-11-28 14:27:10,302 root : HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f792e3e32e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
